# 监听 master 分支
on:
  push:
    branches:
      - master

# action 名称
name: Auto add contributor

jobs:
  # 任务
  contrib-readme-en-job:
    runs-on: ubuntu-latest
    name: A job to auto add contributor  in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}

